### ISSUE TITLE
Committing to master

### ISSUE THREAD

**Issue by crabctrl** [FRC2706/MergeWebServer#1]
I'll stop committing to master once this actually starts getting used, or somebody else starts working on this. Until then, I'm living on the edge

**Comment by ounsworth** [comment]
BWAHAHA <3

**Comment by kevlam2706** [comment]
O_o

**Comment by GabbyGenereux** [comment]
I love it!

**Comment by georgetzavelas** [comment]
Should probably start developing in branches so we don't collide 😄
