### ISSUE TITLE
More JSON integers required for post game.

### ISSUE THREAD

**Issue by Zinka010** [FRC2706/MergeWebServer#26]
We need 2 more integers in the event

**Comment by crabctrl** [comment]
One for deadness and one for time defending. Just putting this here so I don't forget again

**Comment by crabctrl** [comment]
This is completely incompatible with the way events work now. Either we have the app create a "defense" events, or we have to build some kind of match-wide event thing. This would be difficult, but it would also provide a more elegant solution for #5

**Comment by crabctrl** [comment]
@Zinka010 I was thinking the app could just create an event where the goal is "timeDefending" or something and the start time is 0 and end time is however long the team defended for. For example:

If time defending is 30 seconds, you could do:
```
/events/create?match=MATCHKEY&team=TEAMNUMBER&goal="timeDefending"&success=SUCCESS&start=0&end=30&extra=""
```
You could also do `-1` or something for the start time, or do `-1` or `0` for start and end, and use extra to store the value.
It should be simple for the app to find an event with a goal of `timeDefending` and extract the time spent defending...?
