### ISSUE TITLE
Hosting Solution

### ISSUE THREAD

**Issue by georgetzavelas** [FRC2706/MergeWebServer#40]
There was some discussion between Mike and @atoms118 about hosting the app on a different server, largely driven by bandwidth concerns.

Since pictures are not in scope for Ryerson, do we still need to explore this or are we ok with the current server?

**Comment by crabctrl** [comment]
I think the current server should work fine; at the very least we can wait and see how it goes at Ryerson, but I'm willing to bet that with pictures out of the equation the server will be fast enough

**Comment by georgetzavelas** [comment]
👍
