### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by georgetzavelas** [FRC2706/MergeWebServer#8]
It would greatly help debug and usage of the server if we incorporated views into the application. This will allow us see the data as it is updated into the database and to even insert data in a web front end. @atoms118 

Some examples from the previous year (the majority of these views were automatically generated):

## Competitions `index`

<img width="1672" alt="screen shot 2018-01-19 at 8 26 17 pm" src="https://user-images.githubusercontent.com/3611823/35178726-f7bb6ee2-fd5a-11e7-9231-752bdb04c3fa.png">

## Competition `show`

<img width="956" alt="screen shot 2018-01-19 at 8 26 54 pm" src="https://user-images.githubusercontent.com/3611823/35178728-03ae0ef8-fd5b-11e7-9720-8236f2394562.png">

## Match `show`

<img width="1215" alt="screen shot 2018-01-19 at 8 27 20 pm" src="https://user-images.githubusercontent.com/3611823/35178733-16177caa-fd5b-11e7-9a41-97ecf7aa9247.png">

## Match `edit`

<img width="377" alt="screen shot 2018-01-19 at 8 57 34 pm" src="https://user-images.githubusercontent.com/3611823/35178769-87180a5a-fd5b-11e7-87a3-1f6d3d22bc61.png">

## Team `index`

<img width="322" alt="screen shot 2018-01-19 at 8 27 47 pm" src="https://user-images.githubusercontent.com/3611823/35178736-1f6fefc6-fd5b-11e7-962a-2932cf6312d8.png">

## Team `show`

<img width="1089" alt="screen shot 2018-01-19 at 8 28 13 pm" src="https://user-images.githubusercontent.com/3611823/35178740-294ef76c-fd5b-11e7-8af9-947f4b6ad814.png">

## Objective `index`

<img width="1054" alt="screen shot 2018-01-19 at 8 52 51 pm" src="https://user-images.githubusercontent.com/3611823/35178761-734471a8-fd5b-11e7-8b36-0fee6f4c38f3.png">

## Objective `edit`

<img width="333" alt="screen shot 2018-01-19 at 8 56 42 pm" src="https://user-images.githubusercontent.com/3611823/35178764-7a94f59a-fd5b-11e7-8ae2-bbc3221b99a4.png">

**Comment by crabctrl** [comment]
@georgetzavelas what would be the easiest way to do this, since `...#show` and `...#list` is kinda reserved for the app?

**Comment by georgetzavelas** [comment]
You use a different renderer.
Compare this: https://github.com/FRC2706/MergeWebServer/blob/master/app/controllers/competitions_controller.rb#L9
To this: 
https://github.com/FRC2706/scout/blob/master/app/controllers/competitions_controller.rb#L35

**Comment by crabctrl** [comment]
This is helpful but not entirely what I was asking. We want to serve a human different stuff than the app; my question was how do we know whether to server a GUI or JSON? Maybe I'm missing something in the code you gave me though...

**Comment by georgetzavelas** [comment]
When you receive a JSON request, you will respond in JSON, this would be from the app. Conversely if you receive a HTML request, you will respond with HTML, this would be from a browser request. If you have both responses in the controller you can simulate the response by adding `.json` at the end of the URL to get the json output. We can talk about it more tomorrow.

**Comment by crabctrl** [comment]
Ok, so you'd have something like `/teams/list` for HTML and `/teams/list.json` for JSON?

**Comment by georgetzavelas** [comment]
yes

**Comment by crabctrl** [comment]
# Views TODO:
- [x] Possibly some kind of homepage
- [x] teams#list
- [x] teams#show
- [x] competitions#list
- [x] competitions#show
- [x] matches#show
- [ ] events#new
- [x] comments#new
- [ ] pictures#new
- [ ] Syncing with BA

**Comment by crabctrl** [comment]
I'm thinking that syncing with TBA should be available through the web at some point, rather than using the console

**Comment by georgetzavelas** [comment]
That would be cool!
