### ISSUE TITLE
Figure out what's wrong with the SSL

### ISSUE THREAD

**Issue by crabctrl** [FRC2706/MergeWebServer#9]

**Comment by crabctrl** [comment]
According to [this](https://stackoverflow.com/questions/30691476/openssl-error-alert-handshake-failure) and [this](https://stackoverflow.com/questions/4685736/server-name-indication-support-in-nethttp), the issue might be SNI. However, the second answer in the latter question suggests that this has been patched since ruby 2.0, and I'm running 2.3...?

EDIT:
As for the first link, `openssl s_client -connect www.thebluealliance.com:443` does not work, but `openssl s_client -connect www.thebluealliance.com:443 -servername www.thebluealliance.com` does, suggesting that it could be SNI causing the issues

**Comment by ounsworth** [comment]
I spend a lot of time working with SSL. Did you get this sorted out?

**Comment by crabctrl** [comment]
yep
